# Generated by Django 5.2 on 2025-05-19 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rows', models.IntegerField()),
                ('cols', models.IntegerField()),
                ('dots', models.JSONField(default=list, help_text="List of dots, e.g., [{'row': 1, 'col': 2, 'color': '#FF0000'}]")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
