# Generated by Django 5.2 on 2025-05-20 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backgrounds', '0002_gameboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameboard',
            name='dots',
            field=models.JSONField(blank=True, default=list, help_text="List of dots, e.g., [{'row': 1, 'col': 2, 'color': '#FF0000'}]"),
        ),
        migrations.CreateModel(
            name='UserPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_dot', models.JSONField(blank=True, default=dict, help_text="Starting dot position, e.g., {'row': 1, 'col': 2, 'color': '#FF0000'}")),
                ('finishing_dot', models.JSONField(blank=True, default=dict, help_text="Finishing dot position, e.g., {'row': 3, 'col': 4, 'color': '#00FF00'}")),
                ('path_points', models.JSONField(blank=True, default=list, help_text="List of path points, e.g., [{'row': 1, 'col': 2, 'color': '#FF0000'}, {'row': 2, 'col': 3, 'color': '#00FF00'}]")),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backgrounds.gameboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PathsOnBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backgrounds.gameboard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('paths', models.ManyToManyField(related_name='paths_on_board', to='backgrounds.userpath')),
            ],
        ),
    ]
